### ISSUE TITLE
Discuss and decide which DB family to use

### ISSUE THREAD

**Issue by prwteas** [Appsterdam/DataViz#2]
A decision needs to be made on which DB to use with the project. The developer is experienced in SQL types (mySQL) but given the projection of the amount of data to be collected, perhaps another solution could be proposed. Any input highly appreciated...

**Comment by spllr** [comment]
For relational databases I like [postgres](http://www.postgresql.org).

I think a [noSQL](http://en.wikipedia.org/wiki/NoSQL) or [graph database](http://en.wikipedia.org/wiki/Graph_database) can have benefits for this project as well.

Since there is big possibility we will want to collect irregular data (e.g. mine what you can) [MongoDB](http://www.mongodb.org/) could be very helpful.

And since the data we will be pulling out will most likely be graph a solution like [Neo4J](http://neo4j.org/) should be investigated.

Downside off these solutions is off-course the adoption rate and number of people who can work with it, although both MongoDB and Neo4j have been adopted in the Ruby community.

Anyhow, lets make a educated decision.

**Comment by prwteas** [comment]
Have started with MongoDB and admittedly is a very exciting solution. I will be experimenting with it before settling down, but it seems to be a very strong candidate indeed...Neo4j is very appealing too as it is very graphic-orientated and will be investigated in parallel...

**Comment by delware** [comment]
Ok. We have decided to go with Ruby and MonoDB. So this issue can be closed.
